### ISSUE TITLE
Pick component plz

### ISSUE THREAD

**Issue by Sameow** [cs2113-ay1819s2-t11-1/main#26]
Do some small enhancements to a component to learn the code of that component.

pick from here https://nuscs2113-ay1819s2.github.io/addressbook-level4/DeveloperGuide.html#GetStartedProgramming-EachComponent

CREATE ISSUE WITH UR COMPONENT

**Comment by windrichie** [comment]
i'll take the logic component

**Comment by Shizhe-NUS** [comment]
I choose storage component

**Comment by Sameow** [comment]
I choose model component

**Comment by JKupoluyi** [comment]
I'll do the UI component.
