### ISSUE TITLE
Dev guide documentation

### ISSUE THREAD

**Issue by Sameow** [cs2113-ay1819s2-t11-1/main#34]
Each member should describe the implementation of at least one enhancement he has added (or planning to add).

**Comment by JKupoluyi** [comment]
Document how to find mutually available time slots between friends.

**Comment by Shizhe-NUS** [comment]
Do i need to add this to the development guide @Sameow

**Comment by Sameow** [comment]
yea

**Comment by Shizhe-NUS** [comment]
Do i combine all of your description of just my own work @Sameow

**Comment by Sameow** [comment]
update your own part of the dev guide, create PR and we will see what happens

**Comment by Shizhe-NUS** [comment]
create PR against team repo? @Sameow

**Comment by Sameow** [comment]
yup
