### ISSUE TITLE
User guide update

### ISSUE THREAD

**Issue by Sameow** [cs2113-ay1819s2-t11-1/main#35]

**Comment by windrichie** [comment]
- Change user guide title from "AddressBook Level 4 - User Guide" to "Efficient Learning Scheduler - User Guide" 
- Restructure feature descriptions in User Guide

**Comment by JKupoluyi** [comment]
Example of what the UserGuide should look like: https://github.com/nusCS2113-AY1819S2/addressbook-level4/blob/master/docs/UserGuide.adoc

**Comment by Sameow** [comment]
Update with this feature
